// aisdk_docs/examples/next-langchain/app/completion/page.tsx
'use client';

import { useCompletion } from '@ai-sdk/react';

export default function Chat() {
  const { completion, input, handleInputChange, handleSubmit, error } =
    useCompletion({
      api: '/api/completion-string-output-parser',
    });

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      <h4 className="pb-4 text-xl font-bold text-gray-900 md:text-xl">
        useCompletion Example
      </h4>
      {error && (
        <div className="fixed top-0 left-0 w-full p-4 text-center text-white bg-red-500">
          {error.message}
        </div>
      )}
      {completion}
      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}

// aisdk_docs/examples/nuxt-openai/pages/completion/index.vue
<script setup lang="ts">
import { useCompletion } from '@ai-sdk/vue';

const { completion, input, handleSubmit, data } = useCompletion();
</script>

<template>
  <div class="flex flex-col w-full max-w-md py-24 mx-auto stretch">
    <h4 class="pb-4 text-xl font-bold text-gray-900 md:text-xl">
      useCompletion Example
    </h4>
    <pre>{{ data != null ? JSON.stringify(data, null, 2) : '' }}</pre>
    {{ completion }}
    <form @submit="handleSubmit">
      <input
        class="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
        v-model="input"
        placeholder="Say something..."
      />
    </form>
  </div>
</template>
